<a href="https://colab.research.google.com/github/Hit07/ML-DL-Torch/blob/main/Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import Statements


In [3]:
import torch
from torch import tensor,randint
import numpy as np

## Tensors

In [ ]:
# scalars
scalar = tensor(7)
scalar
scalar.ndim

0

In [ ]:
# Gets tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = tensor([7,7])
vector.ndim
vector.shape

torch.Size([2])

In [ ]:
# MATRIX

MATRIX = tensor([[2,3],
                       [4,5]])
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([2, 3])

In [ ]:
# TENSOR

TENSOR = tensor([[[1,2,3],
                       [3,4,5]],

                      [[3,5,3],
                       [4,3,6]],

                      [[0,5,2],
                       [5,8,7]]])
TENSOR.shape


torch.Size([3, 2, 3])

### Random Numbers
Start with random number -> Look at the data -> Update random number -> Repeate the previous steps

In [ ]:
# Creates the size of 3 and 4
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8501, 0.1897, 0.0700, 0.0213],
        [0.2263, 0.3175, 0.9446, 0.4584],
        [0.6781, 0.7064, 0.2786, 0.0957]])

In [ ]:
# Create random image tensor
random_image_tensor = torch.rand(224,224,3) # height,width,colour channel(RGB)
random_image_tensor.shape , random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# Create tensors with zeores and ones

random_zeores = torch.zeros(3,4)
random_ones = torch.ones(3,4)
random_zeores , random_ones

random_ones.dtype

torch.float32

In [ ]:
# Tensors of range and tensors-like
range = torch.arange(11,20)
range

# Tensors-like
range_zeores = torch.zeros_like(input=range)
range_zeores,range


(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([11, 12, 13, 14, 15, 16, 17, 18, 19]))

## Tensors Datatype
Few of the errors we run into with Pytorch and deeplearning:
1. Tensors not right datatype - ```tensor.dtype```
2. Tensors not right shape -  ``` tensor.shape ```
3. Tenosrs not on the right device - ``` tensor.device```


In [33]:
datatype = tensor([2.0,4.0,5.0],
                  dtype=None, # Default datatype is float32
                  device=None)# What device is the tensor on
                  # require_grad=False) # Whether or not to track the gradient with the tensor
datatype.dtype

torch.float32

In [ ]:
float16_tensor = datatype.type(torch.float16)
float16_tensor.dtype

In [ ]:
datatype * float16_tensor

In [ ]:
int32_tensor = tensor([1,3,5],dtype=torch.int32)

datatype*int32_tensor

## Manipulating Tensor (Operations)

* add(),sub(),mul()..

In [ ]:
tensor = tensor([4,5,6])
tensor+100


In [ ]:
tensor * 4

In [ ]:
tensor_1 = tensor-1

## Matrix Multiplication


In [ ]:
torch.matmul(tensor,tensor_1)

In [ ]:
torch.mm(torch.rand(3,3),torch.rand(3,4)) # mm -> matmul

We might end with an error if inner dimension of the matrices donot match while matrix multiplication so deal with issue we can transpose the Matrix -> ``` tensor.T```

In [ ]:
tensorA = torch.randint(1,10,size=(3,2))
tensorB = torch.randint(1,10,size=(3,2))
# torch.mm(tensorA,tensorB) # Shows error
tensorC = torch.mm(tensorA,tensorB.T)
tensorC

## Tensors Aggregation and Positional min and max

* min(),max(),sum(),mean() and other operations

In [ ]:
tensorC.min()
tensorC_float32=tensorC.type(torch.float32)

In [ ]:
tensorC.max(),tensorC_float32.mean() # Mean doesnot work with int64

In [ ]:
range.argmin(),range.argmax()

In [ ]:
range.sum()

## Reshaping, Stacking, Squeezing and Unsqueezing

* **Reshaping**: reshapes a input tensor to defined shape.
* **View**:Retruns a view of an input tensor of certain shape but keeps the same memroy as the original
* **Stacking**: Combines multiple tensors of each other(vstack) and side by side (hstack).
* **Squeez**: removes all```1``` dimesnion from the tensor.
* **Unsqueez**: add a ```1``` dimension to a target tensor.
* **Permute**: Returns a view of the input with dimension permuted(swapped) in a certain way.


In [ ]:
x = torch.arange(1.0,11.0)
x,x.shape

In [ ]:
# Reshape --> Need to be compatible with original shape (factors of it)
reshaped = x.reshape(1,10)
reshaped,reshaped.size()

In [ ]:
# Views --> Its shares the same memeory as the original tensors
view_x = x.view(1,10)
view_x,view_x.shape

In [ ]:
view_x[:,0] = 12
view_x,x

In [ ]:
# Stacking -Horizontally and Vertically

stacked_x = torch.stack([x,x,x],dim=1)
stacked_x

In [ ]:
# Squeez and Unsqueez

squeeze_x = torch.squeeze(input=view_x,dim=0)
squeeze_x,squeeze_x.shape


squeeze_x.unsqueeze(dim=1)

- Permute returns view of the original tensor, changing any values also reflects in the same position

In [ ]:
#Permute - rearranges the dimensions of target tensor specified order
# swapps the dim
#dim1->(,1,)...
random_image_tensor.permute([2,0,1]).shape

## Indexing

* Indexing with Pytorch is similar to indexing with Numpy

In [23]:
import torch
y = torch.arange(1,10).reshape(1,3,3)
y,y.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [25]:
y[0][1]

tensor([4, 5, 6])

In [30]:
y[:,:,0]

tensor([[1, 4, 7]])

In [31]:
y[:,:,2]

tensor([[3, 6, 9]])

## Pytorch tensors & Numpy

* Data in Numpy to Pytorch -> ```torch.from_numpy(ndarray)```
* Pytorch tensor to Numpy -> ```torch.Tensor.numpy()```

**Note**:
* When converting from numpy to Pytorch, pytorch will reflect numpy's default datatype i.e **float64**

* Similarly, when converting form Tensor to Numpy it inherits datatype of default tensor i.e **float32**

In [37]:
#Numpy to Tensor

array = np.array([1.0,2.0,3.0])
pytensor = torch.from_numpy(array)

pytensor,pytensor.dtype

(tensor([1., 2., 3.], dtype=torch.float64), torch.float64)

In [41]:
# Changing the array won't make any changes to tensor and vice-versa(From Tensor to Numpy)
array = array +1
array,pytensor

(array([4., 5., 6.]), tensor([1., 2., 3.], dtype=torch.float64))

In [44]:
# Tensor to Numpy

tensor = torch.ones(7)
np_tensor = tensor.numpy()

tensor , np_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility ( taking random out of randm)

* It enables us to reproduce the same results every time we run our code, which is essential when debugging or evaluating models --> Achieve by setting seed manually

* [Read more...](https://pieriantraining.com/how-to-set-the-seed-in-pytorch-for-reproducible-results/#:~:text=Setting%20the%20Seed%20in%20PyTorch,by%20setting%20the%20seed%20manually.)

In [47]:
seed = 24
torch.manual_seed(seed)
tensorC = torch.rand(3,3)

torch.manual_seed(seed)
tensorD = torch.rand(3,3)


In [48]:
print(tensorC==tensorD)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


## Running Tensors and Pytorch objects on GPUs using CUDA

- We want tensor/Model on the GPU because using a GPU results in faster computation

In [1]:
!nvidia-smi

Thu Jul 11 10:20:23 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [6]:
torch.cuda.is_available()

True

In [29]:
 # Setup device agnostice code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [30]:
# Count number of devices
torch.cuda.device_count()

1

In [17]:
tensor = torch.tensor([1,2,3])
tensor.device

# We can shift the tensor on GPU
tensor_to_gpu  = tensor.to(device)
tensor_to_gpu

tensor([1, 2, 3], device='cuda:0')

In [18]:
# We can convert the tensor_gpu to numpy since it doesn't work
tensor_to_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [23]:
# Moving tensor back to CPU
tensor_to_gpu.cpu().numpy()


array([1, 2, 3])

In [39]:
torch.manual_seed(1234)
torch.cuda.manual_seed(1234)
random_tensor = torch.rand(2,3)

random_tensor

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])

In [37]:
random_tensor = random_tensor.to(device)
random_tensor.device

device(type='cuda', index=0)