<a href="https://colab.research.google.com/github/Hit07/ML-DL-Torch/blob/main/torch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import Statements


In [66]:
import torch
from torch import tensor,randint

## Tensors

In [20]:
# scalars
scalar = tensor(7)
scalar
scalar.ndim

0

In [5]:
# Gets tensor back as Python int
scalar.item()

7

In [21]:
# Vector
vector = tensor([7,7])
vector.ndim
vector.shape

torch.Size([2])

In [25]:
# MATRIX

MATRIX = tensor([[2,3],
                       [4,5]])
MATRIX.ndim

2

In [26]:
MATRIX[0]

tensor([2, 3])

In [28]:
# TENSOR

TENSOR = tensor([[[1,2,3],
                       [3,4,5]],

                      [[3,5,3],
                       [4,3,6]],

                      [[0,5,2],
                       [5,8,7]]])
TENSOR.shape


torch.Size([3, 2, 3])

### Random Numbers
Start with random number -> Look at the data -> Update random number -> Repeate the previous steps

In [37]:
# Creates the size of 3 and 4
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7308, 0.3281, 0.2048, 0.6175],
        [0.0219, 0.5012, 0.7087, 0.2420],
        [0.2267, 0.3124, 0.5524, 0.6101]])

In [39]:
# Create random image tensor
random_image_tensor = torch.rand(224,224,3) # height,width,colour channel(RGB)
random_image_tensor.shape , random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [43]:
# Create tensors with zeores and ones

random_zeores = torch.zeros(3,4)
random_ones = torch.ones(3,4)
random_zeores , random_ones

random_ones.dtype

torch.float32

In [47]:
# Tensors of range and tensors-like
range = torch.arange(11,20)
range

# Tensors-like
range_zeores = torch.zeros_like(input=range)
range_zeores,range


(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([11, 12, 13, 14, 15, 16, 17, 18, 19]))

## Tensors Datatype
Few of the errors we run into with Pytorch and deeplearning:
1. Tensors not right datatype - ```tensor.dtype```
2. Tensors not right shape -  ``` tensor.shape ```
3. Tenosrs not on the right device - ``` tensor.device```


In [52]:
datatype = tensor([2.0,4.0,5.0],
                  dtype=None, # Default datatype is float32
                  device=None,# What device is the tensor on
                  require_grad=False) # Whether or not to track the gradient with the tensor
datatype.dtype

torch.float32

In [53]:
float16_tensor = datatype.type(torch.float16)
float16_tensor.dtype

torch.float16

In [54]:
datatype * float16_tensor

tensor([ 4., 16., 25.])

In [55]:
int32_tensor = tensor([1,3,5],dtype=torch.int32)

datatype*int32_tensor

tensor([ 2., 12., 25.])

## Manipulating Tensor (Operations)

In [67]:
tensor = tensor([4,5,6])
tensor+100


tensor([104, 105, 106])

In [68]:
tensor * 4

tensor([16, 20, 24])

In [71]:
tensor_1 = tensor-1

## Matrix Multiplication


In [74]:
torch.matmul(tensor,tensor_1)

CPU times: user 550 µs, sys: 0 ns, total: 550 µs
Wall time: 453 µs


tensor(62)

In [76]:
torch.mm(torch.rand(3,3),torch.rand(3,4)) # mm -> matmul

tensor([[0.8391, 1.1499, 0.9301, 1.0470],
        [0.8375, 1.2596, 1.0228, 1.0952],
        [0.5125, 0.8886, 0.5035, 0.8592]])

We might end with an error if inner dimension of the matrices donot match while matrix multiplication so deal with issue we can transpose the Matrix -> ``` tensor.T```

In [82]:
tensorA = torch.randint(1,10,size=(3,2))
tensorB = torch.randint(1,10,size=(3,2))
# torch.mm(tensorA,tensorB) # Shows error
tensorC = torch.mm(tensorA,tensorB.T)
tensorC

tensor([[ 73,  64,  17],
        [ 49,  37,  11],
        [112,  97,  26]])

## Tensors Aggregation and Positional min and max

In [92]:
tensorC.min()
tensorC_float32=tensorC.type(torch.float32)

In [95]:
tensorC.max(),tensorC_float32.mean() # Mean doesnot work with int64

(tensor(112), tensor(54.))

In [97]:
range.argmin(),range.argmax()

(tensor(0), tensor(8))

In [98]:
range.sum()

tensor(135)

## Reshaping, Stacking, Squeezing and Unsqueezing

* **Reshaping**: reshapes a input tensor to defined shape.
* **View**:Retruns a view of an input tensor of certain shape but keeps the same memroy as the original
* **Stacking**: Combines multiple tensors of each other(vstack) and side by side (hstack).
* **Squeez**: removes all```1``` dimesnion from the tensor.
* **Unsqueez**: add a ```1``` dimension to a target tensor.
* **Permute**: Returns a view of the input with dimension permuted(swapped) in a certain way.


In [126]:
x = torch.arange(1.0,11.0)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [134]:
# Reshape --> Need to be compatible with original shape (factors of it)
reshaped = x.reshape(1,10)
reshaped,reshaped.size()

(tensor([[12.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [135]:
# Views --> Its shares the same memeory as the original tensors
view_x = x.view(1,10)
view_x,view_x.shape

(tensor([[12.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [131]:
view_x[:,0] = 12
view_x,x

(tensor([[12.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([12.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [132]:
# Stacking -Horizontally and Vertically

stacked_x = torch.stack([x,x,x],dim=1)
stacked_x

tensor([[12., 12., 12.],
        [ 2.,  2.,  2.],
        [ 3.,  3.,  3.],
        [ 4.,  4.,  4.],
        [ 5.,  5.,  5.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  7.],
        [ 8.,  8.,  8.],
        [ 9.,  9.,  9.],
        [10., 10., 10.]])

In [147]:
# Squeez and Unsqueez

squeeze_x = torch.squeeze(input=view_x,dim=0)
squeeze_x,squeeze_x.shape


squeeze_x.unsqueeze(dim=1)

tensor([[12.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])

In [151]:
#Permute - rearranges the dimensions of target tensor specified order
# swapps the dim
#dim1->(,1,)...
random_image_tensor.permute([2,0,1]).shape

torch.Size([3, 224, 224])